// <auto-generated />
using System;
using BuddyApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuddyApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250318135054_UpdateGorevId")]
    partial class UpdateGorevId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuddyApi.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Durum")
                        .HasColumnType("bigint");

                    b.Property<string>("GorevAciklama")
                        .HasColumnType("text");

                    b.Property<string>("GorevAdi")
                        .HasColumnType("text");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<int>("Oncelik")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SonTarih")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("BuddyApi.Models.Planlama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Durum")
                        .HasColumnType("bigint");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<int>("Oncelik")
                        .HasColumnType("integer");

                    b.Property<string>("PlanAciklama")
                        .HasColumnType("text");

                    b.Property<string>("PlanAdi")
                        .HasColumnType("text");

                    b.Property<DateOnly>("TarihAraligi")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Planlar");
                });
#pragma warning restore 612, 618
        }
    }
}
